import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { selectedTerminalFixture } from './helpers/selected-terminal.ts';
import { loadTerminalProcess } from '../core/evidence/final-v2-process.ts';
import { loadContracts } from '../core/measure/inputs.ts';
import { sha256, canonicalBytes } from '../core/measure/identity.ts';
import { createTestNativePiInvocation, authorizeNativePiPayload } from '../core/runtime/native-pi-run.ts';
import { canonicalJson } from '../core/ref/board-artifacts.ts';
import { runNativeFinalReview, finalizeNativeEvidence } from '../core/runtime/native-final-publication.ts';
import { buildNativeFinalManifest } from '../core/runtime/native-final-manifest.ts';
import { validateFinalEvidenceV2GraphFiles } from '../core/evidence/final-v2-graph.ts';
import { nodeStableProjectFileSystem } from '../core/runtime/stable-project-file.ts';
import { reviewProfileBinding } from '../core/runtime/trusted-review-profile.ts';
import { createProjectWriteAdapter } from '../core/runtime/project-write.ts';
import { loadMeasurement } from '../core/measure/files.ts';
import { publishCompletenessRun, publishTypographyApplicability, renderedIrEvidenceBytes } from '../core/completion/evidence.ts';
import { checkTerminalCompletion } from '../core/completion/preflight.ts';
import { receipt, write } from './helpers/measured-terminal.ts';

test('selected art v3 and effective tokens reach isolated profile review and native terminal completion', { timeout: 600_000 }, async t => {
  const f = await selectedTerminalFixture(t), processBinding = loadTerminalProcess(f.root, f.invocation, f.observationSha256s)!;
  assert.equal(processBinding.binding.direction!.record.sha256, f.art.record.sha256);
  assert.equal(processBinding.surfaceRows.length, 2);
  assert.equal(loadContracts(f.root).inputs.find(i => i.kind === 'tokens')!.consumedContractSha256, f.tokens.effectiveTokensSha256);
  const inputPath = join(f.root, '.omd/surface-captures.json'), original = readFileSync(inputPath), omitted = JSON.parse(original.toString('utf8'));
  omitted.captures.pop(); writeFileSync(inputPath, canonicalBytes(omitted));
  assert.throws(() => loadTerminalProcess(f.root, f.invocation, f.observationSha256s), /every required Frame cell/);
  writeFileSync(inputPath, original);
  const nodePath = realpathSync(globalThis.process.execPath), cliPath = fileURLToPath(new URL('fixtures/measured-pi-reviewer-rpc.mjs', import.meta.url));
  const host = { nodePath, nodeSha256: sha256(readFileSync(nodePath)), cliPath, cliSha256: sha256(readFileSync(cliPath)), provider: 'fixture-provider', model: 'fixture-model', thinkingLevel: 'high', parentSessionId: 'selected-parent' };
  const invocation = createTestNativePiInvocation({ root: f.root, host, current: f.invocation.current });
  authorizeNativePiPayload(invocation, f.root, 'product-probe-result', Buffer.from(`${canonicalJson(f.evaluation.receipt)}\n`));
  const reviewed = await runNativeFinalReview({ root: f.root, invocation, signal: t.signal });
  assert.deepEqual(Object.keys(reviewed.lanes), ['blindLane']);
  const lane = JSON.parse(readFileSync(join(f.root, reviewed.lanes.blindLane!.path), 'utf8'));
  assert.deepEqual(lane.fixedBindings.reviewProfile, reviewProfileBinding('blindLane'));
  assert.ok(lane.surfaceReview);
  const activation = Buffer.from(canonicalJson(invocation.activation)), path = `.omd/activation/sha256-${sha256(activation)}.json`;
  createProjectWriteAdapter(f.root, invocation).writeContentAddressed(path, activation);
  const manifest = buildNativeFinalManifest(f.root, invocation, path);
  assert.equal(manifest.graph.schema, 'final-evidence-v2-selected-direction-graph-v1');
  assert.equal(manifest.staticEvidence, undefined);
  assert.equal(validateFinalEvidenceV2GraphFiles(f.root, manifest.graph, nodeStableProjectFileSystem(), invocation).bindings.branch, 'selected-direction');
  const packet = loadMeasurement(f.root, f.measurements[0]!), view = packet.scope.find(v => v.state === 'initial')!, capture = packet.captures.find(c => c.viewId === view.id)!;
  const raw = JSON.parse(readFileSync(join(f.root, capture.ir.path), 'utf8')); raw.meta.url = new URL(view.route, 'http://127.0.0.1').href;
  write(f.root, '.omd/functional-requirements.json', canonicalBytes({ schema: 'functional-requirements-v2', requirements: [{ id: 'R-1', kind: 'content', statement: 'The approved confirmation is visible.', label: 'Approved confirmation sentence.' }], evidence: { states: ['initial'], viewports: [{ width: 1280, height: 900 }, { width: 390, height: 844 }] } }));
  authorizeNativePiPayload(invocation, f.root, 'product-probe-result', renderedIrEvidenceBytes(raw));
  const applicability = publishTypographyApplicability(f.root, raw, invocation);
  publishCompletenessRun(f.root, { schema: 'functional-completeness-run-input-v2', requirements: receipt(f.root, '.omd/functional-requirements.json', 'functional-requirements-v2'), buildIdentity: manifest.graph.buildIdentity,
    sourceSeal: manifest.graph.sourceSeal, typographyApplicability: applicability, testedUrl: raw.meta.url, testedState: 'initial', viewports: [{ width: 1280, height: 900 }, { width: 390, height: 844 }], observations: manifest.graph.observations, findings: [] }, invocation);
  finalizeNativeEvidence({ root: f.root, invocation });
  assert.equal(checkTerminalCompletion(f.root, invocation).final.graph.schema, 'final-evidence-v2-selected-direction-graph-v1');
  const surfacePath = join(f.root, lane.surfaceReview.path), surface = JSON.parse(readFileSync(surfacePath, 'utf8')); surface.rows[0].criteria.hierarchy = 'unassessed';
  writeFileSync(surfacePath, JSON.stringify(surface));
  assert.throws(() => validateFinalEvidenceV2GraphFiles(f.root, manifest.graph, nodeStableProjectFileSystem(), invocation), /bytes changed|changed|stale/);
});
