import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { measurementFixture } from './helpers/visual-measurement.ts';
import { browserFixturePng } from './helpers/browser-observation-decision-links.ts';
import { measureProject } from '../core/measure/index.ts';
import { loadMeasurement } from '../core/measure/files.ts';
import { loadContracts } from '../core/measure/inputs.ts';
import { paint } from '../core/measure/paint.ts';
import { layout } from '../core/measure/layout.ts';
import type { MeasuredIr } from '../core/measure/types.ts';
test('media salience uses captured pixel contrast, not an image element inherited text color', async t => {
  const fixture = measurementFixture('clean'); t.after(() => rmSync(fixture.root, { recursive: true, force: true }));
  writeFileSync(join(fixture.root, 'dist/assets/black.png'), browserFixturePng(32, 32));
  writeFileSync(join(fixture.root, 'dist/index.html'), fixture.html.toString().replace('<main>', '<main><img src="assets/black.png" alt="" style="display:block;width:96px;height:96px;color:white">'));
  const result = await measureProject({ ...fixture, entry: 'dist/index.html' }), packet = loadMeasurement(fixture.root, result.packet);
  const capture = packet.captures[0]!, raw = JSON.parse(readFileSync(join(fixture.root, capture.ir.path), 'utf8')) as MeasuredIr;
  const image = raw.measurement.nodes.find(n => n.tag === 'img')!, pixels = readFileSync(join(fixture.root, capture.capture.path));
  const stats = paint(raw.measurement, pixels);
  assert.deepEqual(image.foreground, [255, 255, 255, 1]);
  assert.equal(stats.mediaContrast.get(image.id), 1);
  const salience = layout(raw.measurement, loadContracts(fixture.root).contracts, stats.canvasPaintShare, stats.mediaContrast)['salience-regions'];
  assert.ok(salience.regions.some(r => r.subjectId === image.id && r.score > 0));
});
