export default function Footer() {
  return (
    <div className="grid footer" id="footer">
      <div className="prose">
        <h2>This page is not a hypothetical demo</h2>
        <p>
          The landing page at 3x-haust.github.io/oh-my-design was generated by OMD itself, from
          one prompt, with the source in <code>example/</code>. This page follows the same loop.
          Source and license: MIT.
        </p>
        <a
          className="cta-label"
          href="https://github.com/3x-haust/oh-my-design"
          target="_blank"
          rel="noreferrer"
        >
          View the source on GitHub
        </a>
      </div>
    </div>
  )
}
